apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: hotel
  labels:
    app: hotel
    component: mongo-express
spec:
  type: NodePort
  selector:
    app: hotel
    component: mongo-express
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
