apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: hotel
  labels:
    app: hotel
    component: mongodb
spec:
  type: ClusterIP
  selector:
    app: hotel
    component: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
