apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hotel
  labels:
    app: hotel
    component: backend
spec:
  type: ClusterIP
  selector:
    app: hotel
    component: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
